nodeLinker: node-modules

npmScopes:
  uzh-uniswap-v3-contracts:
    npmRegistryServer: "https://gitlab.uzh.ch/api/v4/projects/10580/packages/npm/"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"